### ISSUE TITLE
如何配置mysql 不想用h2

### ISSUE THREAD

**Issue by haodedong** [ruibaby/halo#32]
请问如何配置mysql 不想用h2。有sql文件吗

**Comment by ruibaby** [comment]
修改application.yaml配置文件，把h2相关的配置注释掉，然后把mysql相关的注释打开，表是自动建立的，你只需要在mysql把数据库建好就行了，就像下面这样：
```yaml
    # H2database 配置
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/halo/halo
#    username: admin
#    password: 123456

    #MySql配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/halodb?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
```
